import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/ecommerce/Header";
import { EcommerceProvider } from "@/context/ContextEcommerce";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <EcommerceProvider>
      <html lang="en">
        <body className=" bg-white text-black dark:text-white dark:bg-zinc-950">
          <Header />
          <main className="px-2 pt-20 md:px-12 ">{children}</main>
        </body>
      </html>
    </EcommerceProvider>
  );
}
